apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: configmap-manager
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  resourceNames: ["application-config"]
  verbs: ["get", "list", "watch", "update", "patch"]
