apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spring-demo
  template:
    metadata:
      labels:
        app: spring-demo
    spec:
      containers:
      - name: spring-demo
        image: joelowry/spring-demo:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: "1"
            memory: "512Mi"
          requests:
            cpu: "0.5"
            memory: "256Mi"
        volumeMounts:
        - name: config-volume
          mountPath: /config
      imagePullSecrets:
      - name: mydockerhubsecret
      volumes:
      - name: config-volume
        configMap:
          name: application-config
          items:
          - key: application.yml
            path: application.yml
---
apiVersion: v1
kind: Service
metadata:
  name: spring-demo-service
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30000
  selector:
    app: spring-demo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-cloud-kubernetes-configuration-watcher
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-cloud-kubernetes-configuration-watcher
  template:
    metadata:
      labels:
        app: spring-cloud-kubernetes-configuration-watcher
    spec:
      containers:
      - name: spring-cloud-kubernetes-configuration-watcher
        image: springcloud/spring-cloud-kubernetes-configuration-watcher:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: kubernetes
        volumeMounts:
        - name: config-volume
          mountPath: /config
        resources:
          limits:
            cpu: "1"
            memory: "512Mi"
          requests:
            cpu: "0.5"
            memory: "256Mi"
      volumes:
      - name: config-volume
        configMap:
          name: application-config
          items:
          - key: application.yml
            path: application.yml